import React, { useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Share2, Download, Loader2 } from 'lucide-react'; // Loader icon add kiya
import html2canvas from 'html2canvas';

const ShareModal = ({ isOpen, onClose, player }) => {
  const cardRef = useRef(null);
  const [isDownloading, setIsDownloading] = useState(false); // Loading state

  // Ranks based on Level
  const getRank = (lvl) => {
    if (lvl >= 50) return "God Tier";
    if (lvl >= 20) return "Legend";
    if (lvl >= 10) return "Master";
    if (lvl >= 5) return "Warrior";
    return "Rookie";
  };

  // Image Download Logic (FIXED WITH CORS)
  const handleDownload = async () => {
    if (cardRef.current) {
      setIsDownloading(true); // Button loading start
      try {
        // Wait for images to load logic hidden inside html2canvas
        const canvas = await html2canvas(cardRef.current, {
          backgroundColor: '#0f172a',
          scale: 2, // High Quality
          useCORS: true, // <--- YE FIX HAI (External Images allow karta hai)
          allowTaint: true,
          logging: true,
        });
        
        const image = canvas.toDataURL("image/png");
        const link = document.createElement("a");
        link.href = image;
        link.download = `HabitQuest_Lvl${player.level}.png`;
        link.click();
      } catch (error) {
        console.error("Download failed:", error);
        alert("Download failed. Please try again.");
      } finally {
        setIsDownloading(false); // Loading stop
      }
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div 
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          className="fixed inset-0 z-[60] bg-black/90 backdrop-blur-sm flex items-center justify-center p-4"
        >
          <div className="w-full max-w-sm flex flex-col gap-6">
            
            {/* Header */}
            <div className="flex justify-between items-center text-white">
              <h3 className="font-bold uppercase tracking-widest text-sm">Share Profile</h3>
              <button onClick={onClose} className="p-2 bg-slate-800 rounded-full"><X size={20}/></button>
            </div>

            {/* --- THE CARD --- */}
            <div 
              ref={cardRef} 
              className="bg-slate-900 border-2 border-cyan-500 rounded-[32px] p-8 relative overflow-hidden flex flex-col items-center text-center shadow-[0_0_40px_rgba(6,182,212,0.3)]"
            >
              {/* Background Decors */}
              <div className="absolute top-0 left-0 w-full h-32 bg-gradient-to-b from-cyan-500/20 to-transparent"></div>
              
              {/* Avatar (Added crossOrigin prop) */}
              <div className="relative z-10 mb-4">
                <div className="w-28 h-28 rounded-full border-4 border-cyan-400 shadow-xl overflow-hidden bg-slate-800">
                  <img 
                    src={`https://api.dicebear.com/7.x/adventurer/svg?seed=${player.avatarSeed}`} 
                    className="w-full h-full object-cover" 
                    crossOrigin="anonymous" // Important for CORS
                    alt="Avatar"
                  />
                </div>
                <div className="absolute -bottom-3 left-1/2 -translate-x-1/2 bg-yellow-500 text-slate-950 font-black text-xs px-3 py-1 rounded-full border border-yellow-300 uppercase tracking-wider">
                  Level {player.level}
                </div>
              </div>

              {/* Stats */}
              <h2 className="text-2xl font-black italic text-white mb-1 uppercase">{getRank(player.level)}</h2>
              <p className="text-slate-400 text-xs font-bold mb-6 tracking-widest">HABIT QUEST LEGACY</p>

              <div className="grid grid-cols-2 gap-3 w-full mb-6">
                <div className="bg-slate-800/80 p-3 rounded-2xl border border-slate-700">
                  <p className="text-xs text-slate-500 uppercase">Total Gold</p>
                  <p className="text-lg font-black text-yellow-400">🪙 {player.gold}</p>
                </div>
                <div className="bg-slate-800/80 p-3 rounded-2xl border border-slate-700">
                  <p className="text-xs text-slate-500 uppercase">XP Gained</p>
                  <p className="text-lg font-black text-cyan-400">⚡ {player.currentXP}</p>
                </div>
              </div>

              <div className="text-[10px] text-slate-600 font-mono">
                generated by HabitQuest.app
              </div>
            </div>

            {/* Download Button */}
            <button 
              onClick={handleDownload}
              disabled={isDownloading}
              className="w-full bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-black py-4 rounded-xl text-lg shadow-lg shadow-cyan-500/20 active:scale-95 transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isDownloading ? <Loader2 className="animate-spin" /> : <Download size={20} strokeWidth={3} />}
              {isDownloading ? "GENERATING..." : "SAVE IMAGE"}
            </button>

          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default ShareModal;